name: basic_life_support_and_first_aid_app
description: "Basic Life Support and First Aid Educational App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.1
  google_sign_in: ^6.2.2
  google_maps_flutter: ^2.9.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/still_logo.png"

flutter:
  assets:
    - assets/logo_splashscreen.gif
    - assets/still_logo.png
    - assets/triangular_bandage.png
    - assets/wound_dressing.png
    - assets/disposable_gloves.png
    - assets/alcohol.png
    - assets/providone_iodine.png
    - assets/conforming_bandage.png
    - assets/cotton_applicator.png
    - assets/face_mask.png
    - assets/oral_solution.png
    - assets/whistle.png
    - assets/flashlight.png
    - assets/reusable_bandage.png
    - assets/micropore_tape.png
    - assets/scissors.png
    - assets/safety_pin.png
    - assets/tweezers.png
    - assets/multi_purpose_knife.png
    - assets/battery.png
    - assets/glowstick.png
    - assets/garbage_bag.png
    - assets/match_sticks.png
    - assets/profile_placeholder.png
    - assets/sore-eyes.png
    - assets/wounded.png
    - assets/fever.png
    - assets/epilepsy.png
    - assets/heart-attack.png
    - assets/nose-bleeding.png
    - assets/broken-bone.png
    - assets/cerebral.png
    - assets/hospital (1).png
    - assets/facebook.png
    - assets/youtube.png
    - assets/first-aid-kit.png
    - assets/telephone.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  uses-material-design: true
